### ISSUE TITLE
linux

### ISSUE THREAD

**Issue by mktm235** [Nkyoku/pyvcroid2#2]
windows機じゃなくてlinuxでも動きますか？
windowsのボイスロイドなんですが、dllだけlinuxに持ってきても意味ないですか？

**Comment by Nkyoku** [comment]
このライブラリが呼び出すAitalked.dllは非常に基本的なWinAPIしか使用しないので
Wineを使用してDLLを呼び出すだけなら可能かもしれません。
しかし音声変換を利用するためには事前にVOICEROID2エディタを起動してライセンス認証をしておく必要があります。
Wineを用いたVOICEROID2エディタの起動例は確認できなかったためおそらく不可能なのでしょう。
