### ISSUE TITLE
感情パラメータ

### ISSUE THREAD

**Issue by PsycheHeine** [Nkyoku/pyvcroid2#3]
有用なライブラリありがとうございます。
一部のボイスに搭載されている、怒り/悲しみ/喜びの感情に対応予定はございますか？

**Comment by Nkyoku** [comment]
私は該当のボイスロイドを所持しておらず解析できていません。
これに関しては実物がないと開発できないので非対応とさせていただきます。

感情パラメータはパラメータ名+値の組み合わせの辞書を文字列化してDLLに渡しているようなのですが
そのパラメータ名はそれぞれのボイスロイドライブラリのデータファイルが持っているので実物が無いと不明なのです。

**Comment by PsycheHeine** [comment]
ご回答ありがとうございました。
